### ISSUE TITLE
Cannot import cg_custom_core module for custom nodes.  Access refused.

### ISSUE THREAD

**Issue by Nico53425342** [chrisgoringe/cg-noise#19]
Traceback (most recent call last):
  File "C:\Users\nicol\Desktop\Comfy UI Done\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\nicol\Desktop\Comfy UI Done\ComfyUI\custom_nodes\cg-noise\__init__.py", line 2, in <module>
    from .hijack import NODE_CLASS_MAPPINGS as hijack_mappings
  File "C:\Users\nicol\Desktop\Comfy UI Done\ComfyUI\custom_nodes\cg-noise\hijack.py", line 2, in <module>
    from custom_nodes.cg_custom_core.ui_decorator import ui_signal
  File "C:\Users\nicol\Desktop\Comfy UI Done\ComfyUI\custom_nodes\cg_custom_core\__init__.py", line 15, in <module>
    os.remove(old_code_location)
PermissionError: [WinError 5] Accès refusé: 'C:\\Users\\nicol\\Desktop\\Comfy UI Done\\ComfyUI\\web\\extensions\\cg-nodes'

Cannot import C:\Users\nicol\Desktop\Comfy UI Done\ComfyUI\custom_nodes\cg-noise module for custom nodes: [WinError 5] Accès refusé: 'C:\\Users\\nicol\\Desktop\\Comfy UI Done\\ComfyUI\\web\\extensions\\cg-nodes'
Traceback (most recent call last):
  File "C:\Users\nicol\Desktop\Comfy UI Done\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\nicol\Desktop\Comfy UI Done\ComfyUI\custom_nodes\cg_custom_core\__init__.py", line 15, in <module>
    os.remove(old_code_location)
PermissionError: [WinError 5] Accès refusé: 'C:\\Users\\nicol\\Desktop\\Comfy UI Done\\ComfyUI\\web\\extensions\\cg-nodes'

Cannot import C:\Users\nicol\Desktop\Comfy UI Done\ComfyUI\custom_nodes\cg_custom_core module for custom nodes: [WinError 5] Accès refusé: 'C:\\Users\\nicol\\Desktop\\Comfy UI Done\\ComfyUI\\web\\extensions\\cg-nodes'

**Comment by chrisgoringe** [comment]
Could you go into custom_nodes/cg_custom_core and type  
```
git pull
```
and see if that fixes it?

**Comment by Arron17** [comment]
Same issue for me

```
Traceback (most recent call last):
  File "D:\Code\Stable-Diffusion\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Code\Stable-Diffusion\ComfyUI\custom_nodes\cg-noise\__init__.py", line 2, in <module>
    from .hijack import NODE_CLASS_MAPPINGS as hijack_mappings
  File "D:\Code\Stable-Diffusion\ComfyUI\custom_nodes\cg-noise\hijack.py", line 2, in <module>
    from custom_nodes.cg_custom_core.ui_decorator import ui_signal
  File "D:\Code\Stable-Diffusion\ComfyUI\custom_nodes\cg_custom_core\__init__.py", line 15, in <module>
    os.remove(old_code_location)
PermissionError: [WinError 5] Access is denied: 'D:\\Code\\Stable-Diffusion\\ComfyUI\\web\\extensions\\cg-nodes'

Cannot import D:\Code\Stable-Diffusion\ComfyUI\custom_nodes\cg-noise module for custom nodes: [WinError 5] Access is denied: 'D:\\Code\\Stable-Diffusion\\ComfyUI\\web\\extensions\\cg-nodes'
Traceback (most recent call last):
  File "D:\Code\Stable-Diffusion\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Code\Stable-Diffusion\ComfyUI\custom_nodes\cg_custom_core\__init__.py", line 15, in <module>
    os.remove(old_code_location)
PermissionError: [WinError 5] Access is denied: 'D:\\Code\\Stable-Diffusion\\ComfyUI\\web\\extensions\\cg-nodes'

Cannot import D:\Code\Stable-Diffusion\ComfyUI\custom_nodes\cg_custom_core module for custom nodes: [WinError 5] Access is denied: 'D:\\Code\\Stable-Diffusion\\ComfyUI\\web\\extensions\\cg-nodes'
```

I've done a git pull on both cg-noise and cg-custom-core and issue is still present.

**Comment by chrisgoringe** [comment]
Hmmm.

Could you try manually deleting `ComfyUI\web\extensions\cg-nodes` and then restarting Comfy?

**Comment by Nico53425342** [comment]
i did it. but still the same error

**Comment by Arron17** [comment]
On deleting the `web\extensions\cg-nodes` folder, on the next run after cg-noise loads successfully, but cg_custom_core does not.

```
Traceback (most recent call last):
  File "D:\Code\Stable-Diffusion\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Code\Stable-Diffusion\ComfyUI\custom_nodes\cg_custom_core\__init__.py", line 15, in <module>
    os.remove(old_code_location)
PermissionError: [WinError 5] Access is denied: 'D:\\Code\\Stable-Diffusion\\ComfyUI\\web\\extensions\\cg-nodes'

Cannot import D:\Code\Stable-Diffusion\ComfyUI\custom_nodes\cg_custom_core module for custom nodes: [WinError 5] Access is denied: 'D:\\Code\\Stable-Diffusion\\ComfyUI\\web\\extensions\\cg-nodes'
```

If you run it a second time after this, it goes back to both failing to load.

**Comment by chrisgoringe** [comment]
OK - I've removed the dependency on custom_core. Please update and see if it works. You can also remove the custom_nodes/cg_custom_core and ComfyUI\web\extensions\cg-nodes directories.

**Comment by Nico53425342** [comment]
okay i update it now it's the core

Traceback (most recent call last):
  File "C:\Users\nicol\Desktop\Comfy UI Done\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\nicol\Desktop\Comfy UI Done\ComfyUI\custom_nodes\cg_custom_core\__init__.py", line 15, in <module>
    os.remove(old_code_location)
PermissionError: [WinError 5] Accès refusé: 'C:\\Users\\nicol\\Desktop\\Comfy UI Done\\ComfyUI\\web\\extensions\\cg-nodes'

Cannot import C:\Users\nicol\Desktop\Comfy UI Done\ComfyUI\custom_nodes\cg_custom_core module for custom nodes: [WinError 5] Accès refusé: 'C:\\Users\\nicol\\Desktop\\Comfy UI Done\\ComfyUI\\web\\extensions\\cg-nodes'

   0.0 seconds (IMPORT FAILED): C:\Users\nicol\Desktop\Comfy UI Done\ComfyUI\custom_nodes\cg_custom_core

**Comment by chrisgoringe** [comment]
Did you do this:
`You can also remove the custom_nodes/cg_custom_core and ComfyUI\web\extensions\cg-nodes directories.`

**Comment by Nico53425342** [comment]
Thx Chris it work now :)

**Comment by krypt-lx** [comment]
Seems like you need to update installation instruction too: it asks to do "git clone https://github.com/chrisgoringe/cg-custom-core.git cg_custom_core" while cg-custom-core.git doesn't appear to exist anymore

**Comment by chrisgoringe** [comment]
I've retired this node pack. Use https://github.com/chrisgoringe/cg-noisetools
