### ISSUE TITLE
Commit a31edbd breaks the node

### ISSUE THREAD

**Issue by Arron17** [chrisgoringe/cg-noise#9]
a31edbd causes error:
```
Traceback (most recent call last):
  File "D:\Code\Stable-Diffusion\ComfyUI\nodes.py", line 1748, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Code\Stable-Diffusion\ComfyUI\custom_nodes\cg-noise\__init__.py", line 2, in <module>
    from .hijack import NODE_CLASS_MAPPINGS as hijack_mappings
  File "D:\Code\Stable-Diffusion\ComfyUI\custom_nodes\cg-noise\hijack.py", line 2, in <module>
    from custom_nodes.cg_custom_core.ui_decorator import ui_signal
ModuleNotFoundError: No module named 'custom_nodes.cg_custom_core'

Cannot import D:\Code\Stable-Diffusion\ComfyUI\custom_nodes\cg-noise module for custom nodes: No module named 'custom_nodes.cg_custom_core'
```

Looks like it's referencing a module that doesn't exist.
Also on line 48 "Self" is spelt incorrectly

**Comment by chrisgoringe** [comment]
Did you do a manual install? I should add to the documentation - you need to run the install.py script to get the dependency.

**Comment by chrisgoringe** [comment]
Fixed the documentation (and corrected the spelling mistake!)
